# Generated by Django 3.2.16 on 2022-11-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0008_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
