# Generated by Django 3.2 on 2022-10-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0008_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_id',
        ),
    ]
