# Generated by Django 3.2.16 on 2022-11-09 17:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='schedule',
            field=ckeditor.fields.RichTextField(default=None),
            preserve_default=False,
        ),
    ]
