# Generated by Django 3.2.16 on 2022-10-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20221027_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='Noname', max_length=200),
            preserve_default=False,
        ),
    ]
