# Generated by Django 3.2.16 on 2022-11-08 05:24

from django.db import migrations


def change_user_type(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ct = ContentType.objects.filter(
        app_label='auth',
        model='user'
    ).first()
    if ct:
        ct.app_label = 'user'
        ct.save()

class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_userprofile_name'),
    ]

    operations = [
    ]
